name: Create/Update Comment on Pull Request
description: Create/Update Comment on Pull Request
author: everpcpc

inputs:
  token:
    description: GitHub Token
    required: true
  body:
    description: Comment content
    required: true
  files:
    description: Additional comment content from file, split by comma
    required: false
  file-types:
    description: "Content Type for file to show as code, split by comma, empty for not code eg: diff"
    required: false
  file-titles:
    description: collapse with title, split by comma, empty for expand
    required: false
  identifier:
    description: Comment body filter
    required: true
  masks:
    description: "secrets to mask in comment, eg: join(secrets.*)"
    required: false
  masks-split:
    description: "split char for masks"
    required: false
    default: ","
  allow-failure:
    description: allow failure for comment
    required: false
    default: "true"

runs:
  using: node16
  main: dist/index.js

branding:
  icon: message-circle
  color: green
